import React, { useState } from 'react';
import {
  FileCode,
  X,
  Copy,
  CheckCircle,
  Download,
  Activity,
  Mic,
  Layers,
  Zap,
  Bookmark,
} from 'lucide-react';
import {
  type RecordingSession,
  formatDuration,
  generateFullMetadataJSON,
} from '../../auth/SessionStore';

interface AudioMetadataModalProps {
  session: RecordingSession;
  onClose: () => void;
  onExportAudio?: (session: RecordingSession) => void;
}

export const AudioMetadataModal: React.FC<AudioMetadataModalProps> = ({ session, onClose, onExportAudio }) => {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'json'>('overview');

  const jsonString = generateFullMetadataJSON(session);

  const handleCopyJSON = () => {
    navigator.clipboard.writeText(jsonString);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Metadata_${session.title.replace(/\s+/g, '_')}_${session.id}.json`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  };

  const handleDownloadTextReport = () => {
    const txt = `===========================================================
PODCAST CRAFT STUDIO — AUDIO METADATA REPORT
===========================================================
Session Title:    ${session.title}
Session ID:       ${session.id}
Recorded Date:    ${new Date(session.createdAt).toLocaleString()}

PARTICIPANTS:
- Host Speaker:   ${session.hostName} (${session.hostEmail})
- Guest Speaker:  ${session.guestName}

TECHNICAL SPECIFICATIONS:
- Duration:       ${formatDuration(session.durationSeconds)} (${session.durationSeconds} seconds)
- Sample Rate:    ${session.sampleRate || 44100} Hz
- Bit Depth:      ${session.bitDepth || 32}-bit Float
- Channels:       ${session.channelCount} Channels (Stereo Isolation)
- Audio Codec:    ${session.audioCodec || 'PCM IEEE Float 32-bit WAV'}
- Bitrate:        ${session.bitrateKbps || 2822} kbps
- File Size:      ${session.fileSizeMb || 15.4} MB

DSP & LEVEL METRICS:
- Peak Left (Host):   ${session.peakLeftDb ?? -1.5} dBFS
- Peak Right (Guest): ${session.peakRightDb ?? -2.1} dBFS
- Integrated LUFS:    ${session.integratedLufs ?? -16.2} LUFS

CUE POINTS:
${(session.cueMarkers || []).map((m) => `  [${m.time}s] ${m.label}`).join('\n') || '  None'}

Generated by Podcast Craft Studio Metadata Engine v2.0
===========================================================`;

    const blob = new Blob([txt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Report_${session.title.replace(/\s+/g, '_')}_${session.id}.txt`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" onClick={(e) => e.stopPropagation()} style={{ width: '640px', maxWidth: '95vw' }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', borderBottom: '1px solid var(--border-dim)', paddingBottom: '10px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileCode className="daw-logo-icon" size={22} />
            <div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>TECHNICAL AUDIO METADATA INSPECTOR</h3>
              <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>SESSION: {session.id}</div>
            </div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
            <X size={18} />
          </button>
        </div>

        {/* Tab Selector */}
        <div style={{ display: 'flex', gap: '8px', marginBottom: '14px' }}>
          <button
            className={`btn-transport ${activeTab === 'overview' ? 'btn-cyan' : ''}`}
            onClick={() => setActiveTab('overview')}
            style={{ flex: 1 }}
          >
            <Activity size={14} /> Metadata Summary Cards
          </button>
          <button
            className={`btn-transport ${activeTab === 'json' ? 'btn-cyan' : ''}`}
            onClick={() => setActiveTab('json')}
            style={{ flex: 1 }}
          >
            <FileCode size={14} /> Full Raw JSON Payload
          </button>
        </div>

        {activeTab === 'overview' ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {/* Card 1: Session & Participants */}
            <div style={{ background: 'var(--bg-darker)', padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border-dim)' }}>
              <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Mic size={14} color="var(--accent-cyan)" /> SESSION & PARTICIPANTS
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', fontSize: '0.8rem' }}>
                <div><span style={{ color: 'var(--text-muted)' }}>Title:</span> <strong style={{ color: '#fff' }}>{session.title}</strong></div>
                <div><span style={{ color: 'var(--text-muted)' }}>Date:</span> <span>{new Date(session.createdAt).toLocaleString()}</span></div>
                <div><span style={{ color: 'var(--text-muted)' }}>Host Speaker:</span> <span style={{ color: 'var(--accent-cyan)' }}>{session.hostName}</span> ({session.hostEmail})</div>
                <div><span style={{ color: 'var(--text-muted)' }}>Guest Speaker:</span> <span style={{ color: 'var(--accent-amber)' }}>{session.guestName}</span></div>
              </div>
            </div>

            {/* Card 2: Audio Technical Specs */}
            <div style={{ background: 'var(--bg-darker)', padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border-dim)' }}>
              <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Layers size={14} color="var(--accent-green)" /> AUDIO SPECIFICATIONS
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px', fontSize: '0.78rem', fontFamily: 'var(--font-mono)' }}>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>DURATION</div>
                  <div style={{ color: 'var(--accent-green)', fontWeight: 700 }}>{formatDuration(session.durationSeconds)} ({session.durationSeconds}s)</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>SAMPLE RATE</div>
                  <div style={{ color: '#fff' }}>{session.sampleRate || 44100} Hz</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>BIT DEPTH</div>
                  <div style={{ color: '#fff' }}>{session.bitDepth || 32}-bit Float</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>CHANNELS</div>
                  <div style={{ color: '#fff' }}>{session.channelCount} (Stereo L+R)</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>BITRATE</div>
                  <div style={{ color: '#fff' }}>{session.bitrateKbps || 2822} kbps</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>FILE SIZE</div>
                  <div style={{ color: 'var(--accent-cyan)' }}>{session.fileSizeMb || 15.4} MB</div>
                </div>
              </div>
            </div>

            {/* Card 3: DSP & Loudness Levels */}
            <div style={{ background: 'var(--bg-darker)', padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border-dim)' }}>
              <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Zap size={14} color="#c084fc" /> LEVEL & LOUDNESS METRICS
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px', fontSize: '0.78rem', fontFamily: 'var(--font-mono)' }}>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>PEAK HOST (CH L)</div>
                  <div style={{ color: 'var(--accent-cyan)' }}>{session.peakLeftDb ?? -1.5} dBFS</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>PEAK GUEST (CH R)</div>
                  <div style={{ color: 'var(--accent-amber)' }}>{session.peakRightDb ?? -2.1} dBFS</div>
                </div>
                <div>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>INTEGRATED LUFS</div>
                  <div style={{ color: '#c084fc' }}>{session.integratedLufs ?? -16.2} LUFS</div>
                </div>
              </div>
            </div>

            {/* Card 4: Cue Points */}
            <div style={{ background: 'var(--bg-darker)', padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border-dim)' }}>
              <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '6px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Bookmark size={14} color="var(--accent-amber)" /> CUE MARKERS ({(session.cueMarkers || []).length})
              </div>
              <div style={{ fontSize: '0.75rem', fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                {(session.cueMarkers || []).length === 0 ? (
                  <span>No cue points marked during session.</span>
                ) : (
                  (session.cueMarkers || []).map((m) => (
                    <div key={m.id} style={{ display: 'flex', gap: '12px', padding: '2px 0' }}>
                      <span style={{ color: 'var(--accent-cyan)' }}>[{m.time.toFixed(1)}s]</span>
                      <span>{m.label}</span>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        ) : (
          /* JSON Tab */
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <textarea
              readOnly
              value={jsonString}
              style={{
                width: '100%',
                height: '280px',
                background: '#06080d',
                color: 'var(--accent-cyan)',
                fontFamily: 'var(--font-mono)',
                fontSize: '0.75rem',
                padding: '12px',
                borderRadius: '6px',
                border: '1px solid var(--border-dim)',
                resize: 'none',
                outline: 'none',
              }}
            />
          </div>
        )}

        {/* Action Buttons */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '16px', paddingTop: '12px', borderTop: '1px solid var(--border-dim)' }}>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn-transport" onClick={handleDownloadTextReport}>
              <Download size={14} /> .TXT Summary
            </button>
            {onExportAudio && (
              <button
                className="btn-transport btn-cyan"
                onClick={() => {
                  onClose();
                  onExportAudio(session);
                }}
              >
                <Download size={14} /> Export Session WAV Audio
              </button>
            )}
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn-transport" onClick={handleCopyJSON}>
              {copied ? <CheckCircle size={14} color="#00ff87" /> : <Copy size={14} />}
              {copied ? 'Copied JSON' : 'Copy JSON'}
            </button>
            <button className="btn-transport btn-cyan" onClick={handleDownloadJSON}>
              <Download size={14} /> Download Metadata JSON
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
